# Add 'kernel' label to any change within the 'dotnet' directory that's not under 'dotnet/src/SemanticKernel' or 'dotnet/src/SemanticKernel.Abstractions'
kernel:
  - any:
      - "dotnet/**/*"
      - "!dotnet/src/SemanticKernel/**/*"
      - "!dotnet/src/SemanticKernel.Abstractions/**/*"

# Add 'kernel.core' label to any change within the 'SemanticKernel' or 'SemanticKernel.Abstractions' directory
kernel.core:
  - dotnet/src/SemanticKernel/**/*
  - dotnet/src/SemanticKernel.Abstractions/**/*

# Add 'python' label to any change within the 'python' directory
python:
  - python/**/*

# Add 'samples' label to any change within the 'samples' directory
samples:
  - samples/**/*

# Add '.NET' label to any change within samples or kernel 'dotnet' directories.
.NET:
  - dotnet/src/**/*
  - samples/**/dotnet/**/*
